-- 테이블 생성 --
CREATE TABLE my_income_statements (
	YEAR                   INT  NOT NULL,
    MONTH                  INT  NOT NULL,
	MARGINAL_PROFIT        INT  NOT NULL  DEFAULT 0,
    DIVIDEND               INT  NOT NULL  DEFAULT 0,
    INTEREST               INT  NOT NULL  DEFAULT 0,
    NET_MARGINAL_PROFIT    INT  NOT NULL  DEFAULT 0,
    NET_DIVIDEND           INT  NOT NULL  DEFAULT 0,
    NET_INTEREST           INT  NOT NULL  DEFAULT 0,
	PRIMARY KEY(YEAR, MONTH)
);

-- 연 단위(3년) 데이터 검색 (* 파라미터 필요 없음)
SELECT  A.YEAR AS PERIOD , 
        SUM(MARGINAL_PROFIT) AS MARGINAL_PROFIT , 
        (SUM(DIVIDEND) + SUM(INTEREST)) AS DIVIDEND_INTEREST , 
        (SUM(MARGINAL_PROFIT) + SUM(DIVIDEND) + SUM(INTEREST)) AS TOTAL_REVENUE , 
        SUM(NET_MARGINAL_PROFIT) AS NET_MARGINAL_PROFIT ,
        (SUM(NET_DIVIDEND) + SUM(NET_INTEREST)) AS NET_DIVIDEND_INTEREST , 
        (SUM(NET_MARGINAL_PROFIT) + SUM(NET_DIVIDEND) + SUM(NET_INTEREST)) AS TOTAL_NET_INCOME ,
        ( ((SUM(NET_MARGINAL_PROFIT) + SUM(NET_DIVIDEND) + SUM(NET_INTEREST)) / (SUM(MARGINAL_PROFIT) + SUM(DIVIDEND) + SUM(INTEREST))) * 100 ) AS PROFIT_MARGIN_RATE , 
        ( ((SUM(NET_MARGINAL_PROFIT) + SUM(NET_DIVIDEND) + SUM(NET_INTEREST)) / (SUM(DEPOSIT) + SUM(RETAINED_EARNINGS))) * 100 ) AS ROE , 
        ( ((SUM(NET_MARGINAL_PROFIT) + SUM(NET_DIVIDEND) + SUM(NET_INTEREST)) / (SUM(LONG_TERM_LIABILITIES))) ) AS NET_INCOME_LONG_TERM_LIAB
FROM    my_income_statements A , 
        my_balance_sheets B 
WHERE   ( A.YEAR >= YEAR(now())-2 AND A.YEAR <= YEAR(now()) )
        AND A.YEAR = B.YEAR
		AND A.MONTH = B.MONTH
GROUP BY A.YEAR
ORDER BY A.YEAR DESC;

-- 분기 단위(4쿼터) 데이터 검색 (파라미터 : YEAR)
DELIMITER $$ 
DROP PROCEDURE IF EXISTS INCOMES_PER_QUARTER;
CREATE PROCEDURE INCOMES_PER_QUARTER(IN PARAM_year INT)
BEGIN
    DECLARE i INT DEFAULT 1; 
    WHILE (i <= 4) 
    DO
	    SELECT  CONCAT(i, 'Q') AS PERIOD , 
                SUM(MARGINAL_PROFIT) AS MARGINAL_PROFIT , 
                (SUM(DIVIDEND) + SUM(INTEREST)) AS DIVIDEND_INTEREST , 
                (SUM(MARGINAL_PROFIT) + SUM(DIVIDEND) + SUM(INTEREST)) AS TOTAL_REVENUE , 
                SUM(NET_MARGINAL_PROFIT) AS NET_MARGINAL_PROFIT ,
                (SUM(NET_DIVIDEND) + SUM(NET_INTEREST)) AS NET_DIVIDEND_INTEREST , 
                (SUM(NET_MARGINAL_PROFIT) + SUM(NET_DIVIDEND) + SUM(NET_INTEREST)) AS TOTAL_NET_INCOME ,
                ( ((SUM(NET_MARGINAL_PROFIT) + SUM(NET_DIVIDEND) + SUM(NET_INTEREST)) / (SUM(MARGINAL_PROFIT) + SUM(DIVIDEND) + SUM(INTEREST))) * 100 ) AS PROFIT_MARGIN_RATE , 
                ( ((SUM(NET_MARGINAL_PROFIT) + SUM(NET_DIVIDEND) + SUM(NET_INTEREST)) / (SUM(DEPOSIT) + SUM(RETAINED_EARNINGS))) * 100 ) AS ROE , 
                ( ((SUM(NET_MARGINAL_PROFIT) + SUM(NET_DIVIDEND) + SUM(NET_INTEREST)) / (SUM(LONG_TERM_LIABILITIES))) ) AS NET_INCOME_LONG_TERM_LIAB
        FROM    my_income_statements A , 
                my_balance_sheets B 
	    WHERE   A.YEAR = PARAM_year AND ( A.MONTH >= i*3-2 AND A.MONTH <= i*3 )
                AND A.YEAR = B.YEAR
		        AND A.MONTH = B.MONTH
		ORDER BY PERIOD DESC;
        
        SET i = i+1;
    END WHILE;    
END $$
DELIMITER ;
 
CALL INCOMES_PER_QUARTER(2022);

-- 월 단위(3개월) 데이터 검색 (파라미터 : YEAR, QUARTER(1~4))

